# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=120)),
                ('price', models.CharField(choices=[('1', 'R$ 0,00 - R$ 40,00'), ('2', 'R$ 40,00 - R$ 80,00'), ('3', 'R$ 80,00 - R$ 120,00'), ('3', 'R$ 120,00 +')], max_length=1)),
                ('genre', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
