# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170704_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='plataforma',
            new_name='platform',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
