# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20170704_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHiddenPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(blank=True, max_length=120)),
                ('price', models.CharField(blank=True, choices=[('1', 'R$ 0,00 - R$ 40,00'), ('2', 'R$ 40,00 - R$ 80,00'), ('3', 'R$ 80,00 - R$ 120,00'), ('3', 'R$ 120,00 +')], max_length=1)),
                ('genre', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='genre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='platform',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='price',
            field=models.CharField(blank=True, choices=[('1', 'R$ 0,00 - R$ 40,00'), ('2', 'R$ 40,00 - R$ 80,00'), ('3', 'R$ 80,00 - R$ 120,00'), ('3', 'R$ 120,00 +')], max_length=1),
        ),
    ]
